# Generated by Django 3.2.16 on 2023-02-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ui_settings",
            field=models.JSONField(default=dict),
        ),
    ]
