version: '3'
services:
  database:
    image: postgis/postgis:11-3.3
    shm_size: '1024m'
    ports:
      - "5409:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - incidents_network

  api:
    build: ./api
    ports:
      - "8080:8000"
    links:
      - database
      - redis
      # - celery
    env_file:
      - .env
    volumes:
      - ./api:/app
      - ./api/deploy:/deploy
      - ./api/deploy/docker-entrypoint.development.sh:/docker-entrypoint.development.sh
    networks:
      - incidents_network
    command:
      - "/deploy/docker-entrypoint.development.sh"

  redis:
    image: redis
    networks:
      - incidents_network
    ports:
      - "6380:6379"
  # msb:
  #   build: ./msb
  #   ports:
  #     - "8001:8001"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./msb/app/:/build/app
  #   networks:
  #     - incidents_network

volumes:
  postgres-data:

networks:
  incidents_network:
    external: true
