# Generated by Django 3.2.16 on 2022-11-04 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
        ("status", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="incident",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="incidents.incident",
            ),
            preserve_default=False,
        ),
    ]
