# Generated by Django 3.2.16 on 2022-11-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0002_status_incident"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuschoices",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
