# Generated by Django 3.2.16 on 2023-01-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0003_auto_20230118_1546"),
        ("status", "0003_alter_statuschoices_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Status",
        ),
        migrations.DeleteModel(
            name="StatusChoices",
        ),
    ]
