# Generated by Django 3.2.16 on 2022-11-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0002_incident_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
