# Generated by Django 3.2.16 on 2023-01-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0002_incident_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="category",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="location",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="status",
        ),
    ]
