# Generated by Django 3.2.16 on 2022-11-04 14:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=3000)),
            ],
            options={
                'verbose_name': 'Gebiedstype',
                'verbose_name_plural': 'Gebiedstypen',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('gemeente_code', models.CharField(max_length=6, null=True)),
                ('wijk_code', models.CharField(max_length=8, null=True)),
                ('buurt_code', models.CharField(max_length=10, null=True)),
                ('address', models.JSONField(null=True)),
                ('address_text', models.CharField(editable=False, max_length=256, null=True)),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('extra_properties', models.JSONField(null=True)),
                ('bag_validated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
