# Generated by Django 3.2.16 on 2022-11-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_auto_20221109_1513"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
