# Generated by Django 3.2.16 on 2023-01-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0003_auto_20230118_1546"),
        ("locations", "0003_auto_20221109_1513"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="buurt",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="buurt",
            name="_type",
        ),
        migrations.RemoveField(
            model_name="buurt",
            name="wijk",
        ),
        migrations.AlterUniqueTogether(
            name="gemeente",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="gemeente",
            name="_type",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AlterUniqueTogether(
            name="wijk",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="wijk",
            name="_type",
        ),
        migrations.RemoveField(
            model_name="wijk",
            name="gemeente",
        ),
        migrations.DeleteModel(
            name="AreaType",
        ),
        migrations.DeleteModel(
            name="Buurt",
        ),
        migrations.DeleteModel(
            name="Gemeente",
        ),
        migrations.DeleteModel(
            name="Wijk",
        ),
    ]
