# Generated by Django 3.2.16 on 2022-11-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="category",
            name="external_id",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
    ]
