# Generated by Django 3.2.16 on 2022-11-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_auto_20221110_0959"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="external_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("parent", "external_id")},
        ),
    ]
