# Generated by Django 3.2.16 on 2023-01-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_auto_20221114_1647"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
    ]
